### ISSUE TITLE
No permission to an app leads to an app crash and unhandled exception

### ISSUE THREAD

**Issue by WardsParadox** [ripeda/Lectricus#1]
When running this to check apps on my machine, I noticed it was failing to populate any prompts. Looking into the logs when running the CLI gave the reason:
```
Traceback (most recent call last):
  File "lectricus.py", line 8, in <module>
  File "lectricus/command_line.py", line 226, in main
    result = _find_binaries(args.app_directory, args.sys_platform)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lectricus/command_line.py", line 31, in _find_binaries
    return BinarySearch(
           ^^^^^^^^^^^^^
  File "lectricus/binary_search.py", line 24, in __init__
    self._electron_apps = electron_search.Search(**kwargs, variant="electron").apps
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "electron_search/search.py", line 184, in apps
  File "electron_search/search.py", line 112, in _macos_search
  File "pathlib.py", line 1235, in exists
  File "pathlib.py", line 1013, in stat
PermissionError: [Errno 13] Permission denied: '/Applications/QualysCloudAgent.app/Contents/Frameworks/Electron Framework.framework'
```

If I adjust the permissions back to an expected item (755) lectricus works. Color me surprised an AV tool has incorrect permissions.

**Comment by khronokernel** [comment]
Thank you for catching that! The exact source of the issue is here:
* https://github.com/ripeda/Electron-Search/blob/1.3.0/electron_search/search.py#L112-L114

I will add an extra check there for the exception
